DROP DATABASE IF EXISTS EarthBook;
CREATE DATABASE EarthBook;
USE EarthBook;
CREATE TABLE ROLES(
  ID_RO     INT          PRIMARY KEY AUTO_INCREMENT, 
  DESCRIPCION    VARCHAR(20)      NOT NULL UNIQUE
);
  
CREATE TABLE ESTADOS(
  ID_ES     TINYINT          PRIMARY KEY AUTO_INCREMENT, 
  DESCRIPCION    VARCHAR(20)      NOT NULL UNIQUE
  );
  
CREATE TABLE USUARIOS(
  ID_US      INT          PRIMARY KEY AUTO_INCREMENT, 
  DNI   CHAR(8)      NOT NULL UNIQUE,
  NOMBRE    VARCHAR(50)  NOT NULL,
  APELLIDO    VARCHAR(50)  NOT NULL,
  TELEFONO  VARCHAR(10)  NOT NULL UNIQUE,
  DIRECCION VARCHAR(150) NOT NULL,
  CORREO VARCHAR(100) NOT NULL UNIQUE,
  CLAVE  VARCHAR(50)  NOT NULL UNIQUE,
  ID_RO	 	  INT		  NOT NULL,
  ID_ES       TINYINT     NOT NULL DEFAULT 1,
  IMAGEN 	VARCHAR(1000) NOT NULL DEFAULT "https://res.cloudinary.com/dfuuywyk9/image/upload/v1621437436/l60Hf_megote.png",
  FOREIGN KEY (ID_RO) REFERENCES ROLES (ID_RO),
  FOREIGN KEY (ID_ES) REFERENCES ESTADOS (ID_ES)
);

CREATE TABLE CATEGORIAS
(
    ID_CAT       INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(30) NOT NULL UNIQUE,
    IMAGEN 	VARCHAR(1000) NOT NULL DEFAULT "https://res.cloudinary.com/dfuuywyk9/image/upload/v1621437436/l60Hf_megote.png"
);



CREATE TABLE AUTORES
(
    ID_AU       INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(30) NOT NULL UNIQUE,
    BIOGRAFIA VARCHAR(120) NOT NULL UNIQUE,
    IMAGEN 	VARCHAR(1000) NOT NULL DEFAULT "https://res.cloudinary.com/dfuuywyk9/image/upload/v1621437436/l60Hf_megote.png"
);

CREATE TABLE EDITORIALES
(
    ID_ED       INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPCION VARCHAR(30) NOT NULL UNIQUE
);
CREATE TABLE LIBROS
(
    ID_LI      INT PRIMARY KEY AUTO_INCREMENT,
    ISBN		VARCHAR(20)		NOT NULL UNIQUE,
    SKU			VARCHAR(30)		NOT NULL UNIQUE,
    TITULO VARCHAR(100)  NOT NULL UNIQUE,
    DESCRIPCION VARCHAR(350)  NOT NULL UNIQUE,
    PRECIO      DECIMAL(6, 2) NOT NULL CHECK (PRECIO > 0),
    CANTIDAD    TINYINT       NOT NULL CHECK (CANTIDAD >= 0),
    PAGINAS       INT           NOT NULL,
	IMAGEN 	VARCHAR(1000) NOT NULL DEFAULT "https://res.cloudinary.com/dfuuywyk9/image/upload/v1621437436/l60Hf_megote.png",
    ID_AU       INT			NOT NULL,
    ID_ED       INT			NOT NULL,
    ID_CAT       INT			NOT NULL,
    ID_ES       TINYINT     NOT NULL DEFAULT 1,
    FOREIGN KEY (ID_AU) REFERENCES AUTORES (ID_AU),
	FOREIGN KEY (ID_ED) REFERENCES EDITORIALES (ID_ED),
    FOREIGN KEY (ID_CAT) REFERENCES CATEGORIAS (ID_CAT),
    FOREIGN KEY (ID_ES) REFERENCES ESTADOS (ID_ES)
);

CREATE TABLE DISTRITOS
(
    ID_DI  INT PRIMARY KEY AUTO_INCREMENT,
    NOM VARCHAR(50) NOT NULL
);

CREATE TABLE DIRECCION_ENVIOS
(
    ID_EN       INT PRIMARY KEY AUTO_INCREMENT,
	ID_US 	INT NOT NULL,
    DIRECCION  VARCHAR(100) NOT NULL UNIQUE,
    REFERENCIA VARCHAR(100) NOT NULL,
    ID_DI 	INT NOT NULL,
    POSTAL		VARCHAR(10)	NOT NULL,
    FOREIGN KEY(ID_US) REFERENCES USUARIOS(ID_US),
    FOREIGN KEY (ID_DI) REFERENCES DISTRITOS (ID_DI)
);

CREATE TABLE ESTADO_ORDENES(
  ID_ES     TINYINT          PRIMARY KEY AUTO_INCREMENT, 
  DESCRIPCION    VARCHAR(20)      NOT NULL UNIQUE
  );
CREATE TABLE ORDENES
(
    ID_OD          INT 	   NOT NULL AUTO_INCREMENT,
    ID_US         INT     NOT NULL,
    FECHA_PE       DATE    NOT NULL,
    CANTIDAD_TOTAL TINYINT NOT NULL CHECK (CANTIDAD_TOTAL >= 0),
    ID_ES		   TINYINT NOT NULL ,
    ID_EN			INT     NOT NULL,
    PRIMARY KEY (ID_OD, ID_US),
    FOREIGN KEY (ID_ES) REFERENCES ESTADO_ORDENES (ID_ES),
    FOREIGN KEY (ID_EN) REFERENCES DIRECCION_ENVIOS (ID_EN),
    FOREIGN KEY (ID_US) REFERENCES USUARIOS (ID_US)
);
CREATE TABLE DETALLE_ORDENES
(
    ID_OD    INT           NOT NULL,
    ID_LI   INT           NOT NULL,
    SKU 	INT 			NOT NULL,
    PRECIO   DECIMAL(6, 2) NOT NULL CHECK (PRECIO > 0),
    CANTIDAD TINYINT       NOT NULL CHECK (CANTIDAD >= 0),
    IMPORTE  DECIMAL(6, 2) NOT NULL CHECK (IMPORTE > 0),
	FOREIGN KEY (ID_OD) REFERENCES ORDENES (ID_OD),
    FOREIGN KEY (ID_LI) REFERENCES LIBROS (ID_LI)
);
CREATE TABLE BOLETAS
(
    ID_OD     INT           NOT NULL,
    ID_BOL    CHAR(11)      NOT NULL,
    PRETOTAL  DECIMAL(6, 2) NOT NULL,
    DESCUENTO DECIMAL(6, 2) NOT NULL,
    PRIMARY KEY (ID_BOL),
    FOREIGN KEY (ID_OD) REFERENCES DETALLE_ORDENES (ID_OD)
);

INSERT INTO DISTRITOS VALUES (NULL,'LIMA');
INSERT INTO DISTRITOS VALUES (NULL,'ANCON');
INSERT INTO DISTRITOS VALUES (NULL,'ATE');
INSERT INTO DISTRITOS VALUES (NULL,'BARRANCO');
INSERT INTO DISTRITOS VALUES (NULL,'BREÑA');
INSERT INTO DISTRITOS VALUES (NULL,'CARABAYLLO');
INSERT INTO DISTRITOS VALUES (NULL,'CHACLACAYO');
INSERT INTO DISTRITOS VALUES (NULL,'CHORRILLOS');
INSERT INTO DISTRITOS VALUES (NULL,'CIENEGUILLA');
INSERT INTO DISTRITOS VALUES (NULL,'COMAS');
INSERT INTO DISTRITOS VALUES (NULL,'EL AGUSTINO');
INSERT INTO DISTRITOS VALUES (NULL,'INDEPENDENCIA');
INSERT INTO DISTRITOS VALUES (NULL,'JESUS MARIA');
INSERT INTO DISTRITOS VALUES (NULL,'LA MOLINA');
INSERT INTO DISTRITOS VALUES (NULL,'LA VICTORIA');
INSERT INTO DISTRITOS VALUES (NULL,'LINCE');
INSERT INTO DISTRITOS VALUES (NULL,'LOS OLIVOS');
INSERT INTO DISTRITOS VALUES (NULL,'LURIGANCHO');
INSERT INTO DISTRITOS VALUES (NULL,'LURIN');
INSERT INTO DISTRITOS VALUES (NULL,'MAGDALENA DEL MAR');
INSERT INTO DISTRITOS VALUES (NULL,'MAGDALENA VIEJA');
INSERT INTO DISTRITOS VALUES (NULL,'MIRAFLORES');
INSERT INTO DISTRITOS VALUES (NULL,'PACHACAMAC');
INSERT INTO DISTRITOS VALUES (NULL,'PUCUSANA');
INSERT INTO DISTRITOS VALUES (NULL,'PUENTE PIEDRA');
INSERT INTO DISTRITOS VALUES (NULL,'PUNTA HERMOSA');
INSERT INTO DISTRITOS VALUES (NULL,'PUNTA NEGRA');
INSERT INTO DISTRITOS VALUES (NULL,'RIMAC');
INSERT INTO DISTRITOS VALUES (NULL,'SAN BARTOLO');
INSERT INTO DISTRITOS VALUES (NULL,'SAN BORJA');
INSERT INTO DISTRITOS VALUES (NULL,'SAN ISIDRO');
INSERT INTO DISTRITOS VALUES (NULL,'SAN JUAN DE LURIGANCHO');
INSERT INTO DISTRITOS VALUES (NULL,'SAN JUAN DE MIRAFLORES');
INSERT INTO DISTRITOS VALUES (NULL,'SAN LUIS');
INSERT INTO DISTRITOS VALUES (NULL,'SAN MARTIN DE PORRES');
INSERT INTO DISTRITOS VALUES (NULL,'SAN MIGUEL');
INSERT INTO DISTRITOS VALUES (NULL,'SANTA ANITA');
INSERT INTO DISTRITOS VALUES (NULL,'SANTA MARIA DEL MAR');
INSERT INTO DISTRITOS VALUES (NULL,'SANTA ROSA');
INSERT INTO DISTRITOS VALUES (NULL,'SANTIAGO DE SURCO');
INSERT INTO DISTRITOS VALUES (NULL,'SURQUILLO');
INSERT INTO DISTRITOS VALUES (NULL,'VILLA EL SALVADOR');
INSERT INTO DISTRITOS VALUES (NULL,'VILLA MARIA DEL TRIUNFO');

INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('ARTE');
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('CIENCIAS');
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('NOVELA');
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('COMICS');
INSERT INTO CATEGORIAS (DESCRIPCION) VALUES ('MANGA');

INSERT INTO AUTORES (NOMBRE, BIOGRAFIA) VALUES ('CAMUS ALBERT', 'Fue un novelista, ensayista, dramaturgo, filósofo y periodista frances nacido en 1913.');
INSERT INTO AUTORES (NOMBRE, BIOGRAFIA) VALUES ('SEISHI KISHIMOTO', 'Dibujante de manga japonés. Nacio en 1974. Es reconocido por ser el creador de 666 Satan');
INSERT INTO AUTORES (NOMBRE, BIOGRAFIA) VALUES ('JIE ZHANG', 'Es un novelista y cuentista china. Nació en 1986 en Pekin, China');
INSERT INTO AUTORES (NOMBRE, BIOGRAFIA) VALUES ('MOLDES DIEGO', 'Es un escritor español, ensayista, novelista, crítico e historiador de cine. Nació en 1977');
INSERT INTO AUTORES (NOMBRE, BIOGRAFIA) VALUES ('RICARDO PALMA', 'Fue un escritor romantico, costumbrista, tradicionalista, periodista y politico peruano. Nacio en 1833');

INSERT INTO EDITORIALES (DESCRIPCION) VALUES ('RBA LIBROS');

INSERT INTO ESTADOS (DESCRIPCION) VALUES ('ACTIVO');
INSERT INTO ESTADOS (DESCRIPCION) VALUES ('INACTIVO');

INSERT INTO LIBROS (ISBN,SKU,TITULO,DESCRIPCION,PRECIO,CANTIDAD,PAGINAS,ID_AU,ID_ED,ID_CAT)
VALUES ('9788496130965','9788496130965','ARQUIMEDES','Arquímides de Siracusa vivió en tiempos de guerra, por lo que no debe extrañarnos que empleara parte de su genio en diseñar ingeniosas máquinas para la defensa de su ciudad natal.',
14.39,10,152,5,1,2);

INSERT INTO LIBROS (ISBN,SKU,TITULO,DESCRIPCION,PRECIO,CANTIDAD,PAGINAS,ID_AU,ID_ED,ID_CAT)
VALUES ('9788493722838','9788493722838','FALTAN PALABRAS','Una saga generacional femenina que habla de la capacidad de la mujer para sobrevivir a privaciones de toda índole, adaptarse a situaciones particulares o protagonizar el cambio hacia el pensamiento moderno, en un recorrido que nos permite conocer la evolución social de China durante todo el siglo XX.',
14.39,10,333,3,1,3);

INSERT INTO LIBROS (ISBN,SKU,TITULO,DESCRIPCION,PRECIO,CANTIDAD,PAGINAS,ID_AU,ID_ED,ID_CAT)
VALUES ('9788483579312','9788483579312','666 SATAN 01','El éxito de ventas del hermano gemelo del creador de Naruto. 666 Satan recuerda por su dibujo y por el tipo de historia a Naruto. Por ello, cuando salió en Japón, algunos lectores acusaron a Seishi de plagiar a su hermano Masashi.',
21.77,10,192,2,1,5);

INSERT INTO LIBROS (ISBN,SKU,TITULO,DESCRIPCION,PRECIO,CANTIDAD,PAGINAS,ID_AU,ID_ED,ID_CAT)
VALUES ('9789807716284','9789807716284','PESTE','La peste no es una novela sobre las relaciones entre literatura y ciencia, refiere la peste que apodera de la ciudad de Orán, entonces francesa, en los años de la segunda guerra mundial.',
12.47,10,150,1,1,2);

INSERT INTO LIBROS (ISBN,SKU,TITULO,DESCRIPCION,PRECIO,CANTIDAD,PAGINAS,ID_AU,ID_ED,ID_CAT)
VALUES ('9788437630410','9788437630410','ALEJANDRO JODOROWSKY','El cine es una de las muchas disciplinas artísticas que ha cultivado Alejandro Jodorowsky desde hace más de sesenta años. Personaje proteico, escritor (novelista, ensayista, dramaturgo…), autor y guionista de cómics',
73.25,10,496,2,1,4);


